version: "3.0"

networks:
  vyapar_network:
services:

  webapi-vyapar-mhbcn-nic-in:
    container_name: webapi-vyapar-mhbcn-nic-in
    build:
      context: .
      dockerfile: Dockerfile

    image: webapi-vyapar-mhbcn-nic-in:latest
    # environment:
    # - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server      
    ports:
      - 8081:8080
    working_dir: /usr/src/apiServer
    command: sh -c  "node apiserver.js"
    extra_hosts:
      - "peer1.playstationone.vyapar.bcngame.in:10.152.2.120"
      - "peer2.playstationone.vyapar.bcngame.in:10.152.2.120"
      - "peer3.playstationone.vyapar.bcngame.in:10.152.2.120"

      - "peer1.playstationtwo.vyapar.bcngame.in:10.152.2.120"
      - "peer2.playstationtwo.vyapar.bcngame.in:10.152.2.120"
      - "peer3.playstationtwo.vyapar.bcngame.in:10.152.2.120"
      - "peer4.playstationtwo.vyapar.bcngame.in:10.152.2.120"

      - "orderer1.vyapar.bcngame.in:10.152.2.120"
      - "orderer2.vyapar.bcngame.in:10.152.2.120"
      - "orderer3.vyapar.bcngame.in:10.152.2.120"
      - "orderer4.vyapar.bcngame.in:10.152.2.120"
      - "orderer5.vyapar.bcngame.in:10.152.2.120"

      - "ca.vyapar.bcngame.in:10.152.2.120"
      - "tlsca.vyapar.bcngame.in:10.152.2.120"
