"""
Django settings for PIMS project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
print("Starting django from " + str(BASE_DIR))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY', 'django-insecure-v!rixasg-9_5zkht7%s*u3u^xd)xp^!#y1cw+b9*l7e_as6)0k')
# BLOCKCHAIN_API_URL = "http://10.152.2.56:8080/api/"
#BLOCKCHAIN_API_URL = "http://10.152.2.122:8081/api/depotmanager/"
VYAPAR_API_URL = os.environ['VYAPAR_API_URL'] if 'VYAPAR_API_URL' in os.environ else "http://webapi.vyapar.mhbcn.gov.in:8081/api/"

# BLOCKCHAIN_API_URL = "http://10.152.32.243:8081/api/depotmanager/"
# API_URL = "http://localhost:8080/api/"

# VYAPAR_API_URL = "http://webapi.vyapar.mhbcn.gov.in:8081/api/vyapar/"
# API_KEY = 'x-access-token'
# API_KEY_VALUE = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZW1haWwxQGdvdi5pbiIsImlhdCI6MTY0NTYwODM2MywiZXhwIjoxMDI4NTYwODM2M30.0GCjlOAadzNXUKbMBN8hxPUbXrdixinGPY3ogjfp2M'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#DEBUG = os.environ.get('DJANGO_DEBUG', '') != 'False'
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
X_FRAME_OPTIONS = 'SAMEORIGIN'

ALLOWED_HOSTS = ['*']


ROOT_URLCONF = 'PIMS.urls'
WSGI_APPLICATION = 'PIMS.wsgi.application'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Calcutta'
USE_I18N = True
USE_TZ = True

#DATE_FORMAT = 'd-m-Y'
#DATETIME_FORMAT = 'd-m-Y H:i'
#DATE_INPUT_FORMATS = 'd-m-Y'
DATE_INPUT_FORMATS = ('%d-%m-%Y',)


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'EIS',  # 'EIS.apps.EisConfig'
    'rest_framework',
    'crispy_forms',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'PIMS.urls'
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PIMS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# DATABASES = {
#      "default": {
#         "ENGINE": "django.db.backends.postgresql_psycopg2",
#         #"HOST":'localhost',     #os.environ.get('DJANGO_DATABASE_SERVER','localhost'),
#         "HOST":'10.152.32.244',
#         "PORT": os.environ.get('DJANGO_DATABASE_PORT', "5432"),
#         "NAME": 'development_admindb',     #os.environ.get('DJANGO_DATABASE_NAME', "development_admindb"),
#         "USER": os.environ.get('DJANGO_DATABASE_USER', "postgres") ,
#         "PASSWORD":os.environ.get('DJANGO_DATABASE_PASSWORD', "postgres"),
#         "conn_max_age":500,
#      }
# }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# STATIC_ROOT = os.path.join(BASE_DIR, 'static-files')

# 'D:\\Running-Projects\\blockchain_network\\WebApp\\PIMS\\static' # os.path.join(BASE_DIR, '/')
STATIC_ROOT = os.path.join(BASE_DIR, 'static-files')
print(STATIC_ROOT)


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
#STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# MEDIA_URL = '/media/'
# MEDIA_ROOT=os.path.join(BASE_DIR, 'media')
LOGIN_URL = '/eis/'
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
