version: "2.4"

networks:
  blockchain_network:
    external: true
    name: ${DOCKER_NETWORK_NAME}

services:

  ca:
    container_name: ${CA_NAME}
    image: hyperledger/fabric-ca:${FABRIC_CA_VERSION}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=${CA_NAME}
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server/${TLS_CA_NAME}-tls-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server/${TLS_CA_NAME}.key
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/${CA_NAME}-cert.pem
      # - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/server.key
      - FABRIC_LOGGING_SPEC=${LOGGING_LEVEL}
    ports:
      - ${CA_SERVER_PORT}:7054
    # expose:
    #  - "7054"
    working_dir: /etc/hyperledger/fabric-ca-server
    command: sh -c 'fabric-ca-server start -b ${CA_ADMIN_NAME}:${CA_ADMIN_PASSWORD} -d' # -u https://${CA_ADMIN_NAME}:${CA_ADMIN_PASSWORD}@rootca.mhbcn.gov.in:7054 --intermediate.tls.certfiles /etc/hyperledger/fabric-ca-server/rootca/rootca.mhbcn.gov.in-tls-cert.pem'
    
    volumes:
      - ${CA_CRYPTO_PATH}/:/etc/hyperledger/fabric-ca-server
      - ${ROOT_CA_CRYPTO_PATH}/:/etc/hyperledger/fabric-ca-server/rootca
    networks:
      - blockchain_network

  # nginx:
  #   image: nginx:latest
  #   container_name: ${CA_NAME}
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - ca
  #   ports:
  #     - "${CA_SERVER_PORT}:80"