version: "2.4"

networks:
  blockchain_network:
  
    external: true
    name: ${DOCKER_NETWORK_NAME}

services:
  rootca:
    container_name: ${ROOT_CA_NAME}
    image: hyperledger/fabric-ca:${FABRIC_CA_VERSION}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=${ROOT_CA_NAME}
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server/${ROOT_CA_NAME}-tls-cert.pem
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/${ROOT_CA_NAME}-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/priv-key.pem
      - FABRIC_LOGGING_SPEC=${LOGGING_LEVEL}

    ports:
      - ${ROOT_CA_SERVER_PORT}:7054
    working_dir: /etc/hyperledger/fabric-ca-server
    command: sh -c 'fabric-ca-server start -b ${ROOT_CA_ADMIN_NAME}:${ROOT_CA_ADMIN_PASSWORD} -d'    
    volumes:
      - ${ROOT_CA_CRYPTO_PATH}/:/etc/hyperledger/fabric-ca-server
      - ${ROOT_CA_CRYPTO_PATH}/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - blockchain_network




  
