version: "3.0"

networks:
  vyapar_network:
services:

  webapps-vyapar-mhbcn-nic-in:
    container_name: webapps-vyapar-mhbcn-nic-in
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: webapps-vyapar-mhbcn-nic-in:latest

    working_dir: /opt/app

    environment:
      - VYAPAR_BCN_API_URL=http://webapi.vyapar.mhbcn.gov.in:8081/api/
    #   - DJANGO_SUPERUSER_USERNAME=admin
    #   - DJANGO_SUPERUSER_PASSWORD=admin
    #   - DJANGO_SUPERUSER_EMAIL=admin@gov.in

    command: /opt/app/start-gunicorn-server.sh
    
    ports:
      - 8080:8080
    extra_hosts:
      - "webapi.vyapar.mhbcn.gov.in:10.152.2.120"

    networks:
      - vyapar_network
